// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store_grpc.proto

package io.otot.kitten.service.store.grpc;

public final class JRPCServiceProto {
  private JRPCServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JRPCRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.JRPCRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 serialize = 1;</code>
     * @return The serialize.
     */
    int getSerialize();

    /**
     * <code>repeated int64 requestId = 2;</code>
     * @return A list containing the requestId.
     */
    java.util.List<Long> getRequestIdList();
    /**
     * <code>repeated int64 requestId = 2;</code>
     * @return The count of requestId.
     */
    int getRequestIdCount();
    /**
     * <code>repeated int64 requestId = 2;</code>
     * @param index The index of the element to return.
     * @return The requestId at the given index.
     */
    long getRequestId(int index);

    /**
     * <code>string interface = 3;</code>
     * @return The interface.
     */
    String getInterface();
    /**
     * <code>string interface = 3;</code>
     * @return The bytes for interface.
     */
    com.google.protobuf.ByteString
        getInterfaceBytes();

    /**
     * <code>string method = 4;</code>
     * @return The method.
     */
    String getMethod();
    /**
     * <code>string method = 4;</code>
     * @return The bytes for method.
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>repeated string methodSign = 5;</code>
     * @return A list containing the methodSign.
     */
    java.util.List<String>
        getMethodSignList();
    /**
     * <code>repeated string methodSign = 5;</code>
     * @return The count of methodSign.
     */
    int getMethodSignCount();
    /**
     * <code>repeated string methodSign = 5;</code>
     * @param index The index of the element to return.
     * @return The methodSign at the given index.
     */
    String getMethodSign(int index);
    /**
     * <code>repeated string methodSign = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the methodSign at the given index.
     */
    com.google.protobuf.ByteString
        getMethodSignBytes(int index);

    /**
     * <code>repeated bytes arguments = 6;</code>
     * @return A list containing the arguments.
     */
    java.util.List<com.google.protobuf.ByteString> getArgumentsList();
    /**
     * <code>repeated bytes arguments = 6;</code>
     * @return The count of arguments.
     */
    int getArgumentsCount();
    /**
     * <code>repeated bytes arguments = 6;</code>
     * @param index The index of the element to return.
     * @return The arguments at the given index.
     */
    com.google.protobuf.ByteString getArguments(int index);
  }
  /**
   * <pre>
   *请求参数
   * </pre>
   *
   * Protobuf type {@code grpc.JRPCRequest}
   */
  public  static final class JRPCRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.JRPCRequest)
      JRPCRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JRPCRequest.newBuilder() to construct.
    private JRPCRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JRPCRequest() {
      requestId_ = emptyLongList();
      interface_ = "";
      method_ = "";
      methodSign_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      arguments_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new JRPCRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JRPCRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serialize_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                requestId_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              requestId_.addLong(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                requestId_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                requestId_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              interface_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                methodSign_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              methodSign_.add(s);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                arguments_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              arguments_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          requestId_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          methodSign_ = methodSign_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          arguments_ = java.util.Collections.unmodifiableList(arguments_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JRPCServiceProto.internal_static_grpc_JRPCRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JRPCServiceProto.internal_static_grpc_JRPCRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JRPCServiceProto.JRPCRequest.class, JRPCServiceProto.JRPCRequest.Builder.class);
    }

    public static final int SERIALIZE_FIELD_NUMBER = 1;
    private int serialize_;
    /**
     * <code>int32 serialize = 1;</code>
     * @return The serialize.
     */
    public int getSerialize() {
      return serialize_;
    }

    public static final int REQUESTID_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.LongList requestId_;
    /**
     * <code>repeated int64 requestId = 2;</code>
     * @return A list containing the requestId.
     */
    public java.util.List<Long>
        getRequestIdList() {
      return requestId_;
    }
    /**
     * <code>repeated int64 requestId = 2;</code>
     * @return The count of requestId.
     */
    public int getRequestIdCount() {
      return requestId_.size();
    }
    /**
     * <code>repeated int64 requestId = 2;</code>
     * @param index The index of the element to return.
     * @return The requestId at the given index.
     */
    public long getRequestId(int index) {
      return requestId_.getLong(index);
    }
    private int requestIdMemoizedSerializedSize = -1;

    public static final int INTERFACE_FIELD_NUMBER = 3;
    private volatile Object interface_;
    /**
     * <code>string interface = 3;</code>
     * @return The interface.
     */
    public String getInterface() {
      Object ref = interface_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        interface_ = s;
        return s;
      }
    }
    /**
     * <code>string interface = 3;</code>
     * @return The bytes for interface.
     */
    public com.google.protobuf.ByteString
        getInterfaceBytes() {
      Object ref = interface_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        interface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 4;
    private volatile Object method_;
    /**
     * <code>string method = 4;</code>
     * @return The method.
     */
    public String getMethod() {
      Object ref = method_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 4;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODSIGN_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList methodSign_;
    /**
     * <code>repeated string methodSign = 5;</code>
     * @return A list containing the methodSign.
     */
    public com.google.protobuf.ProtocolStringList
        getMethodSignList() {
      return methodSign_;
    }
    /**
     * <code>repeated string methodSign = 5;</code>
     * @return The count of methodSign.
     */
    public int getMethodSignCount() {
      return methodSign_.size();
    }
    /**
     * <code>repeated string methodSign = 5;</code>
     * @param index The index of the element to return.
     * @return The methodSign at the given index.
     */
    public String getMethodSign(int index) {
      return methodSign_.get(index);
    }
    /**
     * <code>repeated string methodSign = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the methodSign at the given index.
     */
    public com.google.protobuf.ByteString
        getMethodSignBytes(int index) {
      return methodSign_.getByteString(index);
    }

    public static final int ARGUMENTS_FIELD_NUMBER = 6;
    private java.util.List<com.google.protobuf.ByteString> arguments_;
    /**
     * <code>repeated bytes arguments = 6;</code>
     * @return A list containing the arguments.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getArgumentsList() {
      return arguments_;
    }
    /**
     * <code>repeated bytes arguments = 6;</code>
     * @return The count of arguments.
     */
    public int getArgumentsCount() {
      return arguments_.size();
    }
    /**
     * <code>repeated bytes arguments = 6;</code>
     * @param index The index of the element to return.
     * @return The arguments at the given index.
     */
    public com.google.protobuf.ByteString getArguments(int index) {
      return arguments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (serialize_ != 0) {
        output.writeInt32(1, serialize_);
      }
      if (getRequestIdList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(requestIdMemoizedSerializedSize);
      }
      for (int i = 0; i < requestId_.size(); i++) {
        output.writeInt64NoTag(requestId_.getLong(i));
      }
      if (!getInterfaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interface_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, method_);
      }
      for (int i = 0; i < methodSign_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, methodSign_.getRaw(i));
      }
      for (int i = 0; i < arguments_.size(); i++) {
        output.writeBytes(6, arguments_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serialize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serialize_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < requestId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(requestId_.getLong(i));
        }
        size += dataSize;
        if (!getRequestIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        requestIdMemoizedSerializedSize = dataSize;
      }
      if (!getInterfaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, interface_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, method_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < methodSign_.size(); i++) {
          dataSize += computeStringSizeNoTag(methodSign_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMethodSignList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arguments_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(arguments_.get(i));
        }
        size += dataSize;
        size += 1 * getArgumentsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof JRPCServiceProto.JRPCRequest)) {
        return super.equals(obj);
      }
      JRPCServiceProto.JRPCRequest other = (JRPCServiceProto.JRPCRequest) obj;

      if (getSerialize()
          != other.getSerialize()) return false;
      if (!getRequestIdList()
          .equals(other.getRequestIdList())) return false;
      if (!getInterface()
          .equals(other.getInterface())) return false;
      if (!getMethod()
          .equals(other.getMethod())) return false;
      if (!getMethodSignList()
          .equals(other.getMethodSignList())) return false;
      if (!getArgumentsList()
          .equals(other.getArgumentsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSerialize();
      if (getRequestIdCount() > 0) {
        hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
        hash = (53 * hash) + getRequestIdList().hashCode();
      }
      hash = (37 * hash) + INTERFACE_FIELD_NUMBER;
      hash = (53 * hash) + getInterface().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      if (getMethodSignCount() > 0) {
        hash = (37 * hash) + METHODSIGN_FIELD_NUMBER;
        hash = (53 * hash) + getMethodSignList().hashCode();
      }
      if (getArgumentsCount() > 0) {
        hash = (37 * hash) + ARGUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getArgumentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static JRPCServiceProto.JRPCRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static JRPCServiceProto.JRPCRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static JRPCServiceProto.JRPCRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(JRPCServiceProto.JRPCRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求参数
     * </pre>
     *
     * Protobuf type {@code grpc.JRPCRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.JRPCRequest)
        JRPCServiceProto.JRPCRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JRPCServiceProto.internal_static_grpc_JRPCRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JRPCServiceProto.internal_static_grpc_JRPCRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JRPCServiceProto.JRPCRequest.class, JRPCServiceProto.JRPCRequest.Builder.class);
      }

      // Construct using io.otot.kitten.service.store.grpc.JRPCServiceProto.JRPCRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        serialize_ = 0;

        requestId_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        interface_ = "";

        method_ = "";

        methodSign_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        arguments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JRPCServiceProto.internal_static_grpc_JRPCRequest_descriptor;
      }

      @Override
      public JRPCServiceProto.JRPCRequest getDefaultInstanceForType() {
        return JRPCServiceProto.JRPCRequest.getDefaultInstance();
      }

      @Override
      public JRPCServiceProto.JRPCRequest build() {
        JRPCServiceProto.JRPCRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public JRPCServiceProto.JRPCRequest buildPartial() {
        JRPCServiceProto.JRPCRequest result = new JRPCServiceProto.JRPCRequest(this);
        int from_bitField0_ = bitField0_;
        result.serialize_ = serialize_;
        if (((bitField0_ & 0x00000001) != 0)) {
          requestId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.requestId_ = requestId_;
        result.interface_ = interface_;
        result.method_ = method_;
        if (((bitField0_ & 0x00000002) != 0)) {
          methodSign_ = methodSign_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.methodSign_ = methodSign_;
        if (((bitField0_ & 0x00000004) != 0)) {
          arguments_ = java.util.Collections.unmodifiableList(arguments_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.arguments_ = arguments_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JRPCServiceProto.JRPCRequest) {
          return mergeFrom((JRPCServiceProto.JRPCRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JRPCServiceProto.JRPCRequest other) {
        if (other == JRPCServiceProto.JRPCRequest.getDefaultInstance()) return this;
        if (other.getSerialize() != 0) {
          setSerialize(other.getSerialize());
        }
        if (!other.requestId_.isEmpty()) {
          if (requestId_.isEmpty()) {
            requestId_ = other.requestId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRequestIdIsMutable();
            requestId_.addAll(other.requestId_);
          }
          onChanged();
        }
        if (!other.getInterface().isEmpty()) {
          interface_ = other.interface_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.methodSign_.isEmpty()) {
          if (methodSign_.isEmpty()) {
            methodSign_ = other.methodSign_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMethodSignIsMutable();
            methodSign_.addAll(other.methodSign_);
          }
          onChanged();
        }
        if (!other.arguments_.isEmpty()) {
          if (arguments_.isEmpty()) {
            arguments_ = other.arguments_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureArgumentsIsMutable();
            arguments_.addAll(other.arguments_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JRPCServiceProto.JRPCRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JRPCServiceProto.JRPCRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serialize_ ;
      /**
       * <code>int32 serialize = 1;</code>
       * @return The serialize.
       */
      public int getSerialize() {
        return serialize_;
      }
      /**
       * <code>int32 serialize = 1;</code>
       * @param value The serialize to set.
       * @return This builder for chaining.
       */
      public Builder setSerialize(int value) {

        serialize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serialize = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerialize() {

        serialize_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList requestId_ = emptyLongList();
      private void ensureRequestIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          requestId_ = mutableCopy(requestId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 requestId = 2;</code>
       * @return A list containing the requestId.
       */
      public java.util.List<Long>
          getRequestIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(requestId_) : requestId_;
      }
      /**
       * <code>repeated int64 requestId = 2;</code>
       * @return The count of requestId.
       */
      public int getRequestIdCount() {
        return requestId_.size();
      }
      /**
       * <code>repeated int64 requestId = 2;</code>
       * @param index The index of the element to return.
       * @return The requestId at the given index.
       */
      public long getRequestId(int index) {
        return requestId_.getLong(index);
      }
      /**
       * <code>repeated int64 requestId = 2;</code>
       * @param index The index to set the value at.
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          int index, long value) {
        ensureRequestIdIsMutable();
        requestId_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 requestId = 2;</code>
       * @param value The requestId to add.
       * @return This builder for chaining.
       */
      public Builder addRequestId(long value) {
        ensureRequestIdIsMutable();
        requestId_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 requestId = 2;</code>
       * @param values The requestId to add.
       * @return This builder for chaining.
       */
      public Builder addAllRequestId(
          Iterable<? extends Long> values) {
        ensureRequestIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, requestId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 requestId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private Object interface_ = "";
      /**
       * <code>string interface = 3;</code>
       * @return The interface.
       */
      public String getInterface() {
        Object ref = interface_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          interface_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string interface = 3;</code>
       * @return The bytes for interface.
       */
      public com.google.protobuf.ByteString
          getInterfaceBytes() {
        Object ref = interface_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          interface_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string interface = 3;</code>
       * @param value The interface to set.
       * @return This builder for chaining.
       */
      public Builder setInterface(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        interface_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string interface = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterface() {

        interface_ = getDefaultInstance().getInterface();
        onChanged();
        return this;
      }
      /**
       * <code>string interface = 3;</code>
       * @param value The bytes for interface to set.
       * @return This builder for chaining.
       */
      public Builder setInterfaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        interface_ = value;
        onChanged();
        return this;
      }

      private Object method_ = "";
      /**
       * <code>string method = 4;</code>
       * @return The method.
       */
      public String getMethod() {
        Object ref = method_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string method = 4;</code>
       * @return The bytes for method.
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 4;</code>
       * @param value The method to set.
       * @return This builder for chaining.
       */
      public Builder setMethod(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethod() {

        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 4;</code>
       * @param value The bytes for method to set.
       * @return This builder for chaining.
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        method_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList methodSign_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMethodSignIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          methodSign_ = new com.google.protobuf.LazyStringArrayList(methodSign_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @return A list containing the methodSign.
       */
      public com.google.protobuf.ProtocolStringList
          getMethodSignList() {
        return methodSign_.getUnmodifiableView();
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @return The count of methodSign.
       */
      public int getMethodSignCount() {
        return methodSign_.size();
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @param index The index of the element to return.
       * @return The methodSign at the given index.
       */
      public String getMethodSign(int index) {
        return methodSign_.get(index);
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the methodSign at the given index.
       */
      public com.google.protobuf.ByteString
          getMethodSignBytes(int index) {
        return methodSign_.getByteString(index);
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @param index The index to set the value at.
       * @param value The methodSign to set.
       * @return This builder for chaining.
       */
      public Builder setMethodSign(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodSignIsMutable();
        methodSign_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @param value The methodSign to add.
       * @return This builder for chaining.
       */
      public Builder addMethodSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodSignIsMutable();
        methodSign_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @param values The methodSign to add.
       * @return This builder for chaining.
       */
      public Builder addAllMethodSign(
          Iterable<String> values) {
        ensureMethodSignIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methodSign_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodSign() {
        methodSign_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodSign = 5;</code>
       * @param value The bytes of the methodSign to add.
       * @return This builder for chaining.
       */
      public Builder addMethodSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMethodSignIsMutable();
        methodSign_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> arguments_ = java.util.Collections.emptyList();
      private void ensureArgumentsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          arguments_ = new java.util.ArrayList<com.google.protobuf.ByteString>(arguments_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes arguments = 6;</code>
       * @return A list containing the arguments.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getArgumentsList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(arguments_) : arguments_;
      }
      /**
       * <code>repeated bytes arguments = 6;</code>
       * @return The count of arguments.
       */
      public int getArgumentsCount() {
        return arguments_.size();
      }
      /**
       * <code>repeated bytes arguments = 6;</code>
       * @param index The index of the element to return.
       * @return The arguments at the given index.
       */
      public com.google.protobuf.ByteString getArguments(int index) {
        return arguments_.get(index);
      }
      /**
       * <code>repeated bytes arguments = 6;</code>
       * @param index The index to set the value at.
       * @param value The arguments to set.
       * @return This builder for chaining.
       */
      public Builder setArguments(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentsIsMutable();
        arguments_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes arguments = 6;</code>
       * @param value The arguments to add.
       * @return This builder for chaining.
       */
      public Builder addArguments(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentsIsMutable();
        arguments_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes arguments = 6;</code>
       * @param values The arguments to add.
       * @return This builder for chaining.
       */
      public Builder addAllArguments(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureArgumentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arguments_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes arguments = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearArguments() {
        arguments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.JRPCRequest)
    }

    // @@protoc_insertion_point(class_scope:grpc.JRPCRequest)
    private static final JRPCServiceProto.JRPCRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new JRPCServiceProto.JRPCRequest();
    }

    public static JRPCServiceProto.JRPCRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JRPCRequest>
        PARSER = new com.google.protobuf.AbstractParser<JRPCRequest>() {
      @Override
      public JRPCRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JRPCRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JRPCRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<JRPCRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public JRPCServiceProto.JRPCRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JRPCResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.JRPCResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 serialize = 1;</code>
     * @return The serialize.
     */
    int getSerialize();

    /**
     * <code>bool successful = 2;</code>
     * @return The successful.
     */
    boolean getSuccessful();

    /**
     * <code>string typeClazz = 3;</code>
     * @return The typeClazz.
     */
    String getTypeClazz();
    /**
     * <code>string typeClazz = 3;</code>
     * @return The bytes for typeClazz.
     */
    com.google.protobuf.ByteString
        getTypeClazzBytes();

    /**
     * <code>bytes body = 4;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * <pre>
   *响应结果
   * </pre>
   *
   * Protobuf type {@code grpc.JRPCResponse}
   */
  public  static final class JRPCResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.JRPCResponse)
      JRPCResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JRPCResponse.newBuilder() to construct.
    private JRPCResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JRPCResponse() {
      typeClazz_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new JRPCResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JRPCResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serialize_ = input.readInt32();
              break;
            }
            case 16: {

              successful_ = input.readBool();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              typeClazz_ = s;
              break;
            }
            case 34: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return JRPCServiceProto.internal_static_grpc_JRPCResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return JRPCServiceProto.internal_static_grpc_JRPCResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JRPCServiceProto.JRPCResponse.class, JRPCServiceProto.JRPCResponse.Builder.class);
    }

    public static final int SERIALIZE_FIELD_NUMBER = 1;
    private int serialize_;
    /**
     * <code>int32 serialize = 1;</code>
     * @return The serialize.
     */
    public int getSerialize() {
      return serialize_;
    }

    public static final int SUCCESSFUL_FIELD_NUMBER = 2;
    private boolean successful_;
    /**
     * <code>bool successful = 2;</code>
     * @return The successful.
     */
    public boolean getSuccessful() {
      return successful_;
    }

    public static final int TYPECLAZZ_FIELD_NUMBER = 3;
    private volatile Object typeClazz_;
    /**
     * <code>string typeClazz = 3;</code>
     * @return The typeClazz.
     */
    public String getTypeClazz() {
      Object ref = typeClazz_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        typeClazz_ = s;
        return s;
      }
    }
    /**
     * <code>string typeClazz = 3;</code>
     * @return The bytes for typeClazz.
     */
    public com.google.protobuf.ByteString
        getTypeClazzBytes() {
      Object ref = typeClazz_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        typeClazz_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 4;</code>
     * @return The body.
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serialize_ != 0) {
        output.writeInt32(1, serialize_);
      }
      if (successful_ != false) {
        output.writeBool(2, successful_);
      }
      if (!getTypeClazzBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, typeClazz_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(4, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serialize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serialize_);
      }
      if (successful_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, successful_);
      }
      if (!getTypeClazzBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, typeClazz_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof JRPCServiceProto.JRPCResponse)) {
        return super.equals(obj);
      }
      JRPCServiceProto.JRPCResponse other = (JRPCServiceProto.JRPCResponse) obj;

      if (getSerialize()
          != other.getSerialize()) return false;
      if (getSuccessful()
          != other.getSuccessful()) return false;
      if (!getTypeClazz()
          .equals(other.getTypeClazz())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERIALIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSerialize();
      hash = (37 * hash) + SUCCESSFUL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccessful());
      hash = (37 * hash) + TYPECLAZZ_FIELD_NUMBER;
      hash = (53 * hash) + getTypeClazz().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static JRPCServiceProto.JRPCResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static JRPCServiceProto.JRPCResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static JRPCServiceProto.JRPCResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(JRPCServiceProto.JRPCResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应结果
     * </pre>
     *
     * Protobuf type {@code grpc.JRPCResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.JRPCResponse)
        JRPCServiceProto.JRPCResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return JRPCServiceProto.internal_static_grpc_JRPCResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return JRPCServiceProto.internal_static_grpc_JRPCResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                JRPCServiceProto.JRPCResponse.class, JRPCServiceProto.JRPCResponse.Builder.class);
      }

      // Construct using io.otot.kitten.service.store.grpc.JRPCServiceProto.JRPCResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        serialize_ = 0;

        successful_ = false;

        typeClazz_ = "";

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return JRPCServiceProto.internal_static_grpc_JRPCResponse_descriptor;
      }

      @Override
      public JRPCServiceProto.JRPCResponse getDefaultInstanceForType() {
        return JRPCServiceProto.JRPCResponse.getDefaultInstance();
      }

      @Override
      public JRPCServiceProto.JRPCResponse build() {
        JRPCServiceProto.JRPCResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public JRPCServiceProto.JRPCResponse buildPartial() {
        JRPCServiceProto.JRPCResponse result = new JRPCServiceProto.JRPCResponse(this);
        result.serialize_ = serialize_;
        result.successful_ = successful_;
        result.typeClazz_ = typeClazz_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof JRPCServiceProto.JRPCResponse) {
          return mergeFrom((JRPCServiceProto.JRPCResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(JRPCServiceProto.JRPCResponse other) {
        if (other == JRPCServiceProto.JRPCResponse.getDefaultInstance()) return this;
        if (other.getSerialize() != 0) {
          setSerialize(other.getSerialize());
        }
        if (other.getSuccessful() != false) {
          setSuccessful(other.getSuccessful());
        }
        if (!other.getTypeClazz().isEmpty()) {
          typeClazz_ = other.typeClazz_;
          onChanged();
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JRPCServiceProto.JRPCResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (JRPCServiceProto.JRPCResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serialize_ ;
      /**
       * <code>int32 serialize = 1;</code>
       * @return The serialize.
       */
      public int getSerialize() {
        return serialize_;
      }
      /**
       * <code>int32 serialize = 1;</code>
       * @param value The serialize to set.
       * @return This builder for chaining.
       */
      public Builder setSerialize(int value) {

        serialize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serialize = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerialize() {

        serialize_ = 0;
        onChanged();
        return this;
      }

      private boolean successful_ ;
      /**
       * <code>bool successful = 2;</code>
       * @return The successful.
       */
      public boolean getSuccessful() {
        return successful_;
      }
      /**
       * <code>bool successful = 2;</code>
       * @param value The successful to set.
       * @return This builder for chaining.
       */
      public Builder setSuccessful(boolean value) {

        successful_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool successful = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccessful() {

        successful_ = false;
        onChanged();
        return this;
      }

      private Object typeClazz_ = "";
      /**
       * <code>string typeClazz = 3;</code>
       * @return The typeClazz.
       */
      public String getTypeClazz() {
        Object ref = typeClazz_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          typeClazz_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string typeClazz = 3;</code>
       * @return The bytes for typeClazz.
       */
      public com.google.protobuf.ByteString
          getTypeClazzBytes() {
        Object ref = typeClazz_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          typeClazz_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string typeClazz = 3;</code>
       * @param value The typeClazz to set.
       * @return This builder for chaining.
       */
      public Builder setTypeClazz(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        typeClazz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string typeClazz = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypeClazz() {

        typeClazz_ = getDefaultInstance().getTypeClazz();
        onChanged();
        return this;
      }
      /**
       * <code>string typeClazz = 3;</code>
       * @param value The bytes for typeClazz to set.
       * @return This builder for chaining.
       */
      public Builder setTypeClazzBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        typeClazz_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 4;</code>
       * @return The body.
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 4;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {

        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.JRPCResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc.JRPCResponse)
    private static final JRPCServiceProto.JRPCResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new JRPCServiceProto.JRPCResponse();
    }

    public static JRPCServiceProto.JRPCResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JRPCResponse>
        PARSER = new com.google.protobuf.AbstractParser<JRPCResponse>() {
      @Override
      public JRPCResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JRPCResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JRPCResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<JRPCResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public JRPCServiceProto.JRPCResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_JRPCRequest_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_JRPCRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_JRPCResponse_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_JRPCResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020store_grpc.proto\022\004grpc\"}\n\013JRPCRequest\022" +
      "\021\n\tserialize\030\001 \001(\005\022\021\n\trequestId\030\002 \003(\003\022\021\n" +
      "\tinterface\030\003 \001(\t\022\016\n\006method\030\004 \001(\t\022\022\n\nmeth" +
      "odSign\030\005 \003(\t\022\021\n\targuments\030\006 \003(\014\"V\n\014JRPCR" +
      "esponse\022\021\n\tserialize\030\001 \001(\005\022\022\n\nsuccessful" +
      "\030\002 \001(\010\022\021\n\ttypeClazz\030\003 \001(\t\022\014\n\004body\030\004 \001(\0142" +
      "?\n\013JRPCService\0220\n\007execute\022\021.grpc.JRPCReq" +
      "uest\032\022.grpc.JRPCResponseB>\n!io.otot.kitt" +
      "en.service.store.grpcB\020JRPCServiceProtoP" +
      "\000\242\002\004OTTOb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_JRPCRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_JRPCRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_JRPCRequest_descriptor,
        new String[] { "Serialize", "RequestId", "Interface", "Method", "MethodSign", "Arguments", });
    internal_static_grpc_JRPCResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_JRPCResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_JRPCResponse_descriptor,
        new String[] { "Serialize", "Successful", "TypeClazz", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
